### ISSUE TITLE
ТЗ

### ISSUE THREAD

**Issue by VektorHL** [VektorHL/HomeForNotAlivePeople#1]
Должен был загрузить сюда. 
Сразу вопрос: за что 4? (Почему не 5?)
[БД. Курсовая. ТЗ.docx](https://github.com/VektorHL/HomeForNotAlivePeople/files/5214981/default.docx)

**Comment by wldmr-key** [comment]
Во-первых, оценка предварительная
во-вторых, плохая кредитная история
в-третьих, ТЗ не убеждает в том, что ты понимаешь специфику продажи ритуальных услуг и их отличие от, скажем, услуг по доставке пиццы

**Comment by VektorHL** [comment]
Хорошо, попробуем исправить. Но учитывая то, что я всё равно магазин буду делать, то тема тоже может измениться. У меня есть ещё несколько на примете.
